apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eric1-rest"
  description: "Testing an application"
  tags:
    - java
    - quarkus
  links:
    - url: https://che-eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/eric1-rest?devfilePath=.devfilev2-theia.yaml
      title: CodeReady Workspaces (Eclipse Theia)
      icon: web
    - url: https://che-eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/eric1-rest?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web    
    - url: https://che-eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/eric1-rest?che-editor=che-incubator/che-idea/next&devfilePath=.devfilev2-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
    - url: https://grafana-route-user-workload-grafana.apps.control-cluster-raffa.demo.red-chesterfield.com/d/AqEG4weWk/error-budget?orgId=1&refresh=5s
      title: SRE metrics (production)
      icon: web    
  annotations:
    github.com/project-slug: etsauer-acme/eric1-rest
    'backstage.io/kubernetes-id': eric1-rest
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=eric1-rest'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "customerdata"
